name: iris_download_manager
description: A download & upload manager.
version: 0.0.2
homepage: https://temp.com

environment:
  sdk: ">=2.17.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  dio: 5.0.1                          # W, https://pub.dev/packages/dio   old:3.0.10

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

# dio use [dart._http] package of skyEngine, no use [http] package
# dio use HttpClient();